update neon-os pkglists

diff --git a/test/neon-os b/test/neon-os
--- a/test/neon-os
+++ b/test/neon-os
@@ -381,21 +381,22 @@ echo "##########################################################################
 echo "########                   ENABLING AUR AND SNAP                    ########"
 echo "############################################################################"
 
-aura_clone_install()
+paru_clone_install()
 {
     internet_connection_check
-    git clone https://aur.archlinux.org/aura-bin.git
-    cd aura-bin
-}
-aura_make_install()
-{
-    aura_clone_install || cd aura-bin
-    makepkg -si
-    internet_connection_check
-    sudo pacman -S neon-os-aura --ask 4 --overwrite=\*
+    git clone https://aur.archlinux.org/paru-bin.git
+    cd paru-bin
 }
 
-aura_make_install || echo "ERROR: Failed to install aura-bin"
+paru_make_install()
+{
+    paru_clone_install || cd paru-bin
+    makepkg -si
+    internet_connection_check
+    sudo pacman -S neon-os-paru --ask 4 --overwrite=\*
+}
+
+paru_make_install || echo "ERROR: Failed to install aura-bin"
 
 cls_n_banner || echo "ERROR: Failed to put banner."
 echo "############################################################################"
@@ -403,7 +404,7 @@ echo "########                   INSTALLING AUR PACKAGES                  ######
 echo "############################################################################"
 
 cd 
-sudo aura -Axa - < neon-os/pkglists/yay.txt --noconfirm --overwrite=\*
+paru -S - < neon-os/pkglists/yay.txt --ask 4 --overwrite=\*
 sudo pacman -S stdm-git --ask 4
 
 cls_n_banner || echo "ERROR: Failed to put banner."
@@ -430,7 +431,7 @@ install_colorizing_program_manually()
 install_colorizing_program()
 {
     internet_connection_check
-    sudo aura -Axa toilet --noconfirm --overwrite=\*
+    paru -S toilet --ask 4 --overwrite=\*
 }
 
 install_colorizing_program || install_colorizing_program_manually || echo "ERROR: Failed to install colorizing program."
@@ -452,7 +453,7 @@ optimus_manager_install()
 	case $answer8 in
 	    "Y" | "y" | "")
 		echo "installing optimus-manager"
-		sudo aura -Axa optimus-manager-qt --noconfirm --overwrite=\*
+		paru -S optimus-manager-qt --ask 4 --overwrite=\*
 		sudo pacman -S neon-os-optimus-manager neon-os-sddm-nvidia --ask 4 --overwrite=\*
 		break;;
 	    "N" | "n")
@@ -628,7 +629,7 @@ tpm_install()
 	case $answer in
 	    "1")
 		echo "installing TPM-1.2"
-		sudo aura -Axa tpm-tools trousers --noconfirm --overwrite=\*
+		paru -S tpm-tools trousers --ask 4 --overwrite=\*
 		modprobe tpm
 		modprobe -a tpm_{atmel,infineon,nsc,tis,crb}
 		sudo systemctl enable tcsd.service
@@ -661,7 +662,7 @@ nextdns_install()
 	case $yn in
 	    "Y" | "y" | "")
 		echo "installing nextdns"
-		sudo aura -Axa nextdns-bin --noconfirm --overwrite=\*
+		paru -S nextdns-bin --ask 4 --overwrite=\*
 		sudo sh -c "$(curl -sL https://nextdns.io/install)"
 		break;;
 	    "N" | "n")
@@ -845,20 +846,13 @@ fail2ban_install()
 
 fail2ban_install || echo "ERROR: Failed to install fail2ban"
 
-# cls_n_banner || echo "ERROR: Failed to put banner."
-# echo "############################################################################"
-# echo "########                  REPLACING SUDO WITH DOAS                  ########"
-# echo "############################################################################"
-
-# sudo chown -c root:root /etc/doas.conf
-# doas -- paru -Qtdq | paru -Rns - sudo
-
 cls_n_banner || echo "ERROR: Failed to put banner."
 echo "############################################################################"
-echo "########                   SETTING UP DOAS                          ########"
+echo "########                  REPLACING SUDO WITH DOAS                  ########"
 echo "############################################################################"
 
 sudo chown -c root:root /etc/doas.conf
+doas -- paru -Qtdq | paru -Rns - sudo
 
 cls_n_banner || echo "ERROR: Failed to put banner."
 echo "############################################################################"
