convert org to md and update chaos installer and update pkglists

diff --git a/chaos b/chaos
--- a/chaos
+++ b/chaos
@@ -113,7 +113,7 @@ update_mirrorlists() {
 	echo "---C----              Configuring mirrors                           ---C----"
 	sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
 	sudo pacman -S reflector rsync --ask 4
-	sudo reflector -l 20 -f 5 -a 48 --sort rate --save /etc/pacman.d/mirrorlist
+	sudo reflector --save /etc/pacman.d/mirrorlist -a 48 -l 20 -f 5 --sort rate --protocol https --verbose --download-timeout 60
 	sudo cp etc/pacman.conf /etc/pacman.conf
 	sudo pacman -Sy neon-os-pacman --overwrite=\* --ask 4
 }
@@ -580,16 +580,12 @@ echo "########                    ENABLING SERVICES                       ######
 echo "############################################################################"
 
 sudo systemctl enable bluetooth || echo "ERROR: Failed to enable bluetooth"
-sudo systemctl enable alsa-state.service alsa-restore.service || echo "ERROR: Failed to enable alsa"
-sudo systemctl enable pulseaudio || echo "ERROR: Failed to enable pulseaudio"
 # sudo systemctl enable reflector.service reflector.timer || echo "ERROR: Failed to enable reflector"
 sudo systemctl enable snapper-timeline.timer snapper-cleanup.timer || echo "ERROR: Failed to enable snapper"
 sudo timedatectl set-ntp true || echo "ERROR: Failed to set ntp time"
 sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket || echo "ERROR: Failed to enable systemd-rfkill"
-systemctl enable --user pipewire.service p11-kit-server.service pulseaudio.service systemd-tmpfiles-clean.timer systemd-tmpfiles-setup.service appimagelauncherd.service gnome-keyring-daemon.service obex.service gcr-ssh-agent.service gpg-agent.service || echo "ERROR: Failed to enable user level services"
-systemctl enable --user jack@.servic || echo "ERROR: Failed to enable user level services"
+systemctl enable --user pipewire.service p11-kit-server.service systemd-tmpfiles-clean.timer systemd-tmpfiles-setup.service appimagelauncherd.service gnome-keyring-daemon.service obex.service gcr-ssh-agent.service gpg-agent.service || echo "ERROR: Failed to enable user level services"
 sudo systemctl enable clamav-freshclam.service clamav-clamonacc.service clamav-daemon.socket || echo "ERROR: Failed to enable clamav"
-sudo systemctl enable libvirtd.service || echo "ERROR: Failed to enable libvirtd"
 sudo systemctl enable set-cfs-tweaks.service || echo "ERROR: Failed to enable cfs tweaks"
 sudo systemctl enable asd.service asd-resync.service asd-resync.timer || echo "ERROR: Failed to enable anything-sync-daemon"
 
@@ -630,9 +626,16 @@ echo "##########################################################################
 echo "########                  ADDING USER TO GROUPS                     ########"
 echo "############################################################################"
 
-sudo usermod -aG kvm,libvirt,libvirt-qemu ${USER} || echo "ERROR: Failed to add ${USER} in kvm, libvirt & libvirt-qemu groups"
+sudo usermod -aG kvm,vboxusers ${USER} || echo "ERROR: Failed to add ${USER} in kvm, vboxusers groups"
 
 cls_n_banner || echo "ERROR: Failed to put banner."
+
+echo "############################################################################"
+echo "########             LOADING VIRTUALBOX KERNEL MODULES              ########"
+echo "############################################################################"
+
+sudo rcvboxdrv modprobe
+
 echo "############################################################################"
 echo "########                      SETTING UP TPM                        ########"
 echo "############################################################################"
