update neon-os pkglists test

diff --git a/neon-os b/neon-os
--- a/neon-os
+++ b/neon-os
@@ -220,7 +220,7 @@ ucode_install || echo "ERROR: Failed to install cpu ucode"
 
 internet_connection_check
 echo "---C----              Installing my packages                        ---C----"
-sudo pacman -S - < pkglists/pacman.txt --overwrite=\* --ask 4 --ask 4
+sudo pacman -S - < pkglists/pacman.txt --overwrite=\* --ask 4
 
 multiple_monitors()
 {
@@ -381,15 +381,17 @@ sudo systemctl enable reflector.service reflector.timer || echo "ERROR: Failed t
 sudo systemctl enable snapper-timeline.timer snapper-cleanup.timer || echo "ERROR: Failed to enable snapper"
 sudo timedatectl set-ntp true || echo "ERROR: Failed to set ntp time"
 sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket || echo "ERROR: Failed to enable systemd-rfkill"
-systemctl enable --user pipewire.service p11-kit-server.service pulseaudio.service systemd-tmpfiles-clean.timer systemd-tmpfiles-setup.service || echo "ERROR: Failed to enable user level services"
+systemctl enable --user pipewire.service p11-kit-server.service pulseaudio.service systemd-tmpfiles-clean.timer systemd-tmpfiles-setup.service appimagelauncherd.service gnome-keyring-daemon.service obex.service gcr-ssh-agent.service gpg-agent.service || echo "ERROR: Failed to enable user level services"
+systemctl enable --user jack@.servic || echo "ERROR: Failed to enable user level services"
 sudo systemctl enable clamav-freshclam.service clamav-clamonacc.service clamav-daemon.socket || echo "ERROR: Failed to enable clamav"
 sudo systemctl enable libvirtd.service || echo "ERROR: Failed to enable libvirtd"
 sudo systemctl enable set-cfs-tweaks.service || echo "ERROR: Failed to enable cfs tweaks"
 sudo systemctl enable asd.service asd-resync.service asd-resync.timer || echo "ERROR: Failed to enable anything-sync-daemon"
+psd 2> /dev/null 1> /dev/null
 sudo systemctl enable psd.service psd-resync.service || echo "ERROR: Failed to enable profile-sync-daemon"
 
 cd ~/neon-os
-sudo mkdir -p /usr/local/lib/systemd/user/
+sudo mkdir -p ~/.config/systemd/user/ || "ERROR: Folder already exists"
 cp services/* .config/systemd/user/
 systemctl --user daemon-reload
 systemctl enable --user emacs.service ssh-agent.service imwheel.service || echo "ERROR: Failed to enable emacs ssh and imwheel services"
@@ -441,6 +443,48 @@ tpm_install()
     fi
 }
 tpm_install || echo "ERROR: Failed to install tpm driver"
+
+echo "############################################################################"
+echo "########                     INSTALLING NEXTDNS                     ########"
+echo "############################################################################"
+
+nextdns_install()
+{
+    internet_connection_check
+    read -p "do you want to install nextdns [Y/N]? " yn
+    if [[ $yn == "Y" || $yn == "y" || $yn == "" ]]
+    then
+	echo "installing nextdns"
+	paru -S nextdns-bin --ask 4
+	sudo sh -c "$(curl -sL https://nextdns.io/install)"
+    else
+	echo "terminated"
+    fi
+}
+nextdns_install || echo "ERROR: Failed to install nextdns"
+
+echo "############################################################################"
+echo "########                    DISABLING WATCHDOGS                     ########"
+echo "############################################################################"
+
+watchdog_blacklist()
+{
+    read -p "do you want to disable watchdog [Y/N]? " yn
+    var=`mkinitcpio -M | grep wdt`
+    if [[ $var == "iTCO_wdt" ]]
+    then
+	if [[ $yn == "y" || $yn == "Y" || $yn == "" ]]
+	then
+	    echo "disabling watchdog"
+	    sudo pacman -S neon-os-watchdog-blacklist --ask 4 --overwrite=\*
+	else
+	    echo "terminated"
+	fi
+    else
+	echo -e "At present the script does not \nsupport disabling other types of \nwatchdogs but it would be included in the next release. \nIf you want to still disable the watchdog you can refer to \nthis arch wiki page ===> https://wiki.archlinux.org/title/improving_performance#Watchdogs \nand this blog post ===> https://linuxhint.com/linux-kernel-watchdog-explained/"
+    fi
+}
+watchdog_blacklist || echo "ERROR: Failed to blacklist watchdog kernel module"
 
 echo "############################################################################"
 echo "########                  REPLACING SUDO WITH DOAS                  ########"
